name: Build and Release PDF

on:
  pull_request_target:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: install wkhtmltopdf & fonts
        run: |
          sudo apt-get update
          sudo apt-get install wkhtmltopdf fonts-noto-cjk
          fc-cache -fv
      - name: html to pdf
        run: wkhtmltopdf --enable-local-file-access index.html index.pdf
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: index.pdf
          tag_name: ${{ github.head_ref }}-release
          draft: false
          prerelease: true
          generate_release_notes: true
